# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226d2f66c86f0ca614f9d586210e785c7188cad6f8856a72d31efac3bdeaee6414446318d5704d1bab4e37fc66aade528555c20d300e4a8f98c7afbfb00a7966

test:
  secret_key_base: 792ab1d4de6fbd5064d76a03cfeea65ba79a89d272bf4b507a4b4b0c4d308652c1594056cc43ce4a7b0a54843e5d12b6af6b2507d6563ea5b815cafddde7a128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
